name: kismet
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/random.svg
    - assets/icons/dice.png
    - assets/icons/random-number.png
    - assets/icons/coin.png
    - assets/icons/dice_game/1.png
    - assets/icons/dice_game/2.png
    - assets/icons/dice_game/3.png
    - assets/icons/dice_game/4.png
    - assets/icons/dice_game/5.png
    - assets/icons/dice_game/6.png
    - assets/icons/coin_game/heads.png
    - assets/icons/coin_game/tails.png
    - assets/icons/random_number_game/0.png
    - assets/icons/random_number_game/1.png
    - assets/icons/random_number_game/2.png
    - assets/icons/random_number_game/3.png
    - assets/icons/random_number_game/4.png
    - assets/icons/random_number_game/5.png
    - assets/icons/random_number_game/6.png
    - assets/icons/random_number_game/7.png
    - assets/icons/random_number_game/8.png
    - assets/icons/random_number_game/9.png
    - assets/icons/random_number_game/10.png
    - assets/icons/splash_screen_icon.png





  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf

